name: CI - Orchestrator

on:
  push:
    branches:
      - develop
      - ci/**
  pull_request:

jobs:
  checkstyle:
    uses: ./.github/workflows/checkstyle.yml

  pmd:
    uses: ./.github/workflows/pmd.yml

  spotbugs:
    uses: ./.github/workflows/spotbugs.yml

  unit-test:
    uses: ./.github/workflows/unit-test.yml
    needs:
      - checkstyle
      - pmd
      - spotbugs
